# Generated by Django 3.0.4 on 2020-03-23 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pais',
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='tipo',
            field=models.CharField(choices=[('FN', 'Fake New'), ('HS', 'Harassment'), ('H', 'Hate'), ('N', 'Nudes'), ('PP', 'Personal Profit'), ('S', 'Spam'), ('SS', 'Suicide or Self-harm'), ('T', 'Terrorism'), ('V', 'Violence'), ('S', 'Others')], default='FN', max_length=30),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Usuario'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fuente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='FN', max_length=10),
        ),
    ]
