# Generated by Django 3.0.4 on 2020-03-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200322_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagen',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='email',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
