# Generated by Django 3.0.4 on 2020-03-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_denuncia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
