# Generated by Django 3.0.4 on 2020-03-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200324_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='puntaje',
            field=models.IntegerField(null=True),
        ),
    ]
